## Good tutorial on yaml properities - https://www.baeldung.com/spring-yaml, https://www.baeldung.com/properties-with-spring
management:
   endpoints:
      web:
         exposure:
            include: "*" 

## Database Properties
spring:
   jpa:
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   datasource:
      url: jdbc:mysql://localhost:3306/teamchatdb
      username: rkuser
      password: RkUser12

